-- | This module contains opaque types declared in multiple Nix C API headers simultaneously.
-- Haskell code generated by hs-bindgen cannot share/reuse those duplicated opaque types.
-- To work around it, we manualy define them here and write an external binding specification.
module Nix.Api.OpaqueTypes
  ( EvalState,
    Nix_value,
  )
where

-- NOTE handle more opaque types of nix_api_expr_internal.h when needed

-- we follow hs-bindgen's naming logic
{- HLINT ignore "Use camelCase" -}

data EvalState

data Nix_value
